<h1 class="no-display">Building materials and supplies</h1>

<?php if (($_productCollection = $this->getProductCollection()) && $_productCollection->getSize()): ?>

<div id="lastProducts" class="block" style="border-radius: 3px 3px 3px 3px;">
  <div class="listing-type-grid catalog-listing latest-products">
    <h2>Latest products</h2>

    <?php $_collectionSize = $_productCollection->count() ?>

    <table cellspacing="0" class="generic-product-grid" id="product-list-table">

    <?php $_columnCount = 3; ?>
    <?php $i = 0; foreach ($_productCollection as $_product): ?>

    <?php if ($i++ % $_columnCount == 0): ?>
    <tr>
    <?php endif ?>
      <td>
        <p class="product-image">
          <a class="preview" rel="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 300); ?>" href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')); ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(215, 170); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')); ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')); ?>" />
          </a>
        </p>

        <h3>
          <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->htmlEscape($_product->getName()); ?>"><?php echo $this->htmlEscape($_product->getName()); ?></a>
        </h3>

        <?php if($_product->getRatingSummary()): ?>
          <?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?>
        <?php endif; ?>

        <?php echo $this->getPriceHtml($_product, true); ?>

        <?php if($_product->isSaleable()): ?>
        <a href="#" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product); ?>')" class="add-to-cart"><?php echo $this->__('Add to Cart + '); ?></a>
        <?php else: ?>
        <div class="out-of-stock"><?php echo $this->__('Out of stock'); ?></div>
        <?php endif; ?>

        <div class="clear"></div>

        <ul class="add-to">
          <?php if ($this->helper('wishlist')->isAllow()) : ?>
          <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product); ?>"><?php echo $this->__('Add to Wishlist'); ?></a></li>
          <?php endif; ?>

          <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
          <li><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare'); ?></a></li>
          <?php endif; ?>
        </ul>
      </td>
    <?php if ($i % $_columnCount == 0 && $i != $_collectionSize): ?>
    </tr>
    <?php endif ?>

    <?php endforeach ?>

    <?php for($i; $i % $_columnCount != 0; $i++): ?>
        <td class="empty-product">&nbsp;</td>
    <?php endfor ?>

    <?php if ($i % $_columnCount == 0): ?>
    </tr>
    <?php endif ?>

    </table>

    <script type="text/javascript">decorateTable('product-list-table')</script>

  </div>
</div>
<?php endif; ?>
