<?php

/**
 * Productivity
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE-AFL.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category  ZetaPrints
 * @package   ZetaPrints_Productivity
 * @copyright Copyright (c) 2014 ZetaPrints Ltd. (http://www.zetaprints.com)
 * @license   http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 */

?>

<?php

$helper = Mage::helper('core');

?>

<div id="productivity-image-edit-panel" class="tm-image-editor-menu">
  <div class="set-main-image"
       title="<?php echo $this->__('Set as main image'); ?>">
  </div>

  <div class="remove-image"
       title="<?php echo $this->__('Remove'); ?>">
  </div>

  <div class="rotate-image rotate-left"
       title="<?php echo $this->__('Rotate left'); ?>">
  </div>

  <div class="rotate-image rotate-right"
       title="<?php echo $this->__('Rotate right'); ?>">
  </div>
</div>

<script type="text/javascript">
//<![CDATA[

productivity.image.url = {
  rotate: '<?php echo $this->getUrl('productivity/image/rotate') ?>',
  remove: '<?php echo $this->getUrl('productivity/image/remove') ?>',
  setmain: '<?php echo $this->getUrl('productivity/image/setmain') ?>'
};

productivity.edit.selector = {
  image: '<?php echo $this->getImageSelector() ?>',
  thumbnail: '<?php echo $this->getThumbSelector() ?>'
};

productivity.edit.wrapper = {
  image: '<?php echo $this->getImageWrapperSelector() ?>',
  thumbnail: '<?php echo $this->getThumbWrapperSelector() ?>'
};

productivity.edit.size = {
  image: <?php echo $helper->jsonEncode($this->getImageSize()) ?>,
  thumbnail: <?php echo $helper->jsonEncode($this->getThumbSize()) ?>
};

//]]>
</script>
