<?php if ($this->isAdmin()): ?>
<style>
.admin-button{
position: fixed;
top: 0px;
right: 0px;
background: white;
border: 1px solid black;
opacity: 0.8;
padding: 2px;
border-top: 0px;
font-size: 11px;
}
.admin-button:hover{
background:#fffafa;
}
.admin-button a {
color:black;
text-decoration:none;
}
</style>
<div class="admin-button">
<?php
// get page type
$pageType = $this->getRequest()->getControllerName();


if($pageType=='product'){
	$currentProduct = Mage::registry('product');
	echo "<a href = '" . Mage::helper("adminhtml")->getUrl("adminhtml/catalog_product/edit",array("id"=>$currentProduct->getId())) . "'>Product in admin</a>";
	
}
if($pageType == 'page' || $pageType == 'index'){
	$currentPage = $this->getHelper('cms/page')->getPage()->getData();
	if ($currentPage) {
		echo "<a href = '" . Mage::helper("adminhtml")->getUrl("sampleapp/adminhtml_index/index",array("page_id"=>$currentPage['page_id'])) . "'>CMS page in admin</a>";
	}  
}
if($pageType=='category') {
  $currentCategory = Mage::registry('current_category');
  if($currentCategory) {
  	echo "<a href = '" . Mage::helper("adminhtml")->getUrl("adminhtml/catalog_category/edit/",array("id"=>$currentCategory->getId())) . "'>Category in admin</a>";
  }
}
?>
</div>
<?php endif ?>
