<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE-OSL.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package MVentory/Productivity
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

?>

<?php

$_id = $this->getElementId();
$_class = $this->getAdditionalClass();

$_id = $_id ? 'id="' . $_id . '" ' : '';
$_class = 'class="productivity-rss-wrapper'
          . ($_class ? ' ' . $_class : '')
          . '"';

?>

<div <?php echo $_id, $_class; ?>>
  <?php echo $this->getContent(); ?>
</div>
