<?php

/**
 * Productivity
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE-AFL.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category  ZetaPrints
 * @package   ZetaPrints_Productivity
 * @copyright Copyright (c) 2014 ZetaPrints Ltd. (http://www.zetaprints.com)
 * @license   http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 */

?>

<?php

$_id = $this->getElementId();
$_class = $this->getAdditionalClass();

$_id = $_id ? 'id="' . $_id . '" ' : '';
$_class = 'class="productivity-rss-wrapper'
          . ($_class ? ' ' . $_class : '')
          . '"';

?>

<div <?php echo $_id, $_class; ?>>
  <?php echo $this->getContent(); ?>
</div>
