<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE-OSL.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package MVentory/Productivity
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

?>

<div class="productivity-config-hint">
  Logged in Admins and Customers from group Reviewers can access some admin functions via Productivity Toolbar in the front end.
  <br />
  See <a target="_blank" href="https://github.com/mVentory/MVentory_Productivity/">project page</a> for documentation and source code. Check out our <a target="_blank" href="http://mventory.com/why-mventory/">Android app</a> for Magento admin.
</div>