<?php if (Mage::helper('MvProductivityPack')->isAdminLogged()) : ?>

<script type="text/javascript">
//<![CDATA[

_tm_image_editor_rotate_url = '<?php echo $this->getUrl('mvproductivitypackf/image/rotate') ?>';
_tm_image_editor_remove_url = '<?php echo $this->getUrl('mvproductivitypackf/image/remove') ?>';
_tm_image_editor_setmain_url = '<?php echo $this->getUrl('mvproductivitypackf/image/setmain') ?>';

//]]>
</script>

<?php endif; ?>
