<?php if (Mage::helper('MvProductivityPack')->isReviewerLogged()) : ?>

<?php

$_productId = Mage::registry('product')->getId();
$_url = $this->getUrl('mvproductivitypackf/image/upload');

?>

<script type="text/javascript">
//<![CDATA[

jQuery(function ($) {

var $upload_elem = $('#productivity-uploader-element');
var $upload_btn = $('#productivity-uploader-button-upload');

$upload_elem
  .fineUploader({
    button: $('#productivity-uploader-dropzone'),
    listElement: $('#productivity-uploader-previews'),

    request: {
      endpoint: '<?php echo $_url; ?>',
      params: {
        product_id: <?php echo $_productId; ?>
      }
    },

    dragAndDrop: {
      disableDefaultDropzone: true,
      hideDropzones: false,
      extraDropzones: [$('#productivity-uploader-dropzone')]
    },

    text: {
      cancelButton: ''
    }
  })
  .on('submitted', function (event, id, name) {
    var $this = $(this);
    var reader = new FileReader();

    reader.onload = function (e) {
      $this
        .fineUploader('getItemByFileId', id)
        .css('background-image', 'url(' + e.target.result + ')');
    };

    reader.readAsDataURL($this.fineUploader('getFile', id));

    $upload_btn.css('display', 'block');
  })
  .on('complete', function (event, id, name, response, xhr) {
    if (!response.success)
      return;

    if (typeof productivity === 'undefined')
      return;

    function on_error ($element, data) {
      $element
        .removeClass('qq-upload-success')
        .addClass('qq-upload-fail');

      setTimeout(
        function () { $element.removeClass('qq-upload-fail'); },
        5000
      );
    }

    productivity.func.add_panel(
      $(this).fineUploader('getItemByFileId', id),
      {
        panel: {
          position: { top: 2, left: 2 },
          scope: 'uploader',
          action: {
            remove: {
              on_error: on_error,
              on_success: function ($element, data) {
                $element.remove();
              }
            },
            rotate: {
              on_error: on_error,
              on_success: function ($element, data) {
                $element.css('background-image', 'url(' + data.url + ')');
                $element.data('productivity').file = data.file;
              }
            },
            setmain: {
              on_error: on_error,
              on_success: function ($element, data) {
                $element.image.prop('src', data.image.url);
                $element.image.data('productivity').file = data.image.file;
              }
            }
          }
        },
        image: {
          file: response.data.file,
          type: 'thumbnail',
          width: null,
          height: null
        }
      }
    );
  });

$upload_btn.on('click', function () {
  $upload_elem.fineUploader('uploadStoredFiles');
});

});

//]]>
</script>

<?php endif; ?>
