<?php

/**
 * Productivity
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE-AFL.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category  ZetaPrints
 * @package   ZetaPrints_Productivity
 * @copyright Copyright (c) 2014 ZetaPrints Ltd. (http://www.zetaprints.com)
 * @license   http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 */


/**
 * Mouse middle button click for attributes
 */

?>

<script>
var attribute = <?php echo $this->getJson() ?>;
var key = '<?php echo Mage::getSingleton('adminhtml/url')->getSecretKey("catalog_product_attribute","edit");?>';
Event.observe(window, 'load', function() {
  $$('.x-tree-node-leaf').each(function(item) {
    item.down('a').observe('mousedown', function(event){
      if(Event.isMiddleClick(event)) {
        event.preventDefault();
        var id = attribute[event.target.innerHTML];
        window.open('/admin/catalog_product_attribute/edit/attribute_id/'+id+'/key/'+key+'/', '_blank');
      }
    });
  });
});
</script>