<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE-OSL.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package MVentory/Productivity
 * @copyright Copyright (c) 2014-215 mVentory Ltd. (http://mventory.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

?>

<script>
var attributeUrls = <?php echo $this->getJson() ?>;

Event.observe(window, 'load', function() {
  $$('.x-tree-node-leaf').each(function(item) {
    var attr = item.down('a').down('span').innerHTML,
        url = attributeUrls[attr];

    item.insert(new Element(
      'a',
      {
        href: url,
        class: 'fa fa-pencil',
        target: '_blank',

        /**
         * @todo This should be a translatable string
         */
        title: 'Open attribute\'s editor...'
      }
    ));
  });
});
</script>
