<?php 
  $a = array();
  $collection = Mage::getResourceModel('catalog/product_attribute_collection');
  foreach($collection as $attribute) {
    $a[$attribute->getData('attribute_code')] = $attribute->getData('attribute_id');;
  }
  $a = json_encode($a);
?>
<script>
var attribute = <?php echo $a ?>;
var key = '<?php echo Mage::getSingleton('adminhtml/url')->getSecretKey("catalog_product_attribute","edit");?>';
Event.observe(window, 'load', function() { 
  $$('.x-tree-node-leaf').each(function(item) {
    item.down('a').observe('mousedown', function(event){
      if(Event.isMiddleClick(event)) {
        event.preventDefault();
        var id = attribute[event.target.innerHTML];
        window.open('/admin/catalog_product_attribute/edit/attribute_id/'+id+'/key/'+key+'/', '_blank');  
      } 
    });
  }); 
}); 
</script>