<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE-OSL.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package MVentory/Productivity
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

?>

<script>
var categories = <?php echo $this->getJson() ?>;
var key = '<?php echo Mage::getSingleton('adminhtml/url')->getSecretKey("catalog_product_attribute","edit");?>';
Event.observe(window, 'load', function() {
  $('front-button').observe('click', function() {
      var id = $$('input[name="general[id]"]')[0].value;
      if(id > 0) {
        var url = categories[id];
        window.open(url);
      }
  });
    $('category-edit-container').observe('mousedown', function(e) {
      if(Event.isMiddleClick(e)) {
        var tr = e.target.up('tr');
        if(tr && e.target.up('table.data') && e.target.tagName == 'TD') {
          var id = tr.down('input[type="checkbox"]').value;
          window.open('/admin/catalog_product/edit/id/'+id+'/key/'+key+'/');
        }
      }

    });
});
</script>
<div class="frontshop-button">
  <button id="front-button" type="button" class="scalable frontshop"><span><?php echo $this->__('FrontShop Preview') ?></span></button>
</div>