<script>
var categories = <?php echo $this->getJson() ?>;
var key = '<?php echo Mage::getSingleton('adminhtml/url')->getSecretKey("catalog_product_attribute","edit");?>';
Event.observe(window, 'load', function() {
  $('front-button').observe('click', function() { 
      var id = $$('input[name="general[id]"]')[0].value;
      if(id > 0) {
        var url = categories[id];
        window.open(url);   
      }
  }); 
    $('category-edit-container').observe('mousedown', function(e) {
      if(Event.isMiddleClick(e)) {
        var tr = e.target.up('tr');
        if(tr && e.target.up('table.data') && e.target.tagName == 'TD') {
          var id = tr.down('input[type="checkbox"]').value;
          window.open('/admin/catalog_product/edit/id/'+id+'/key/'+key+'/');
        }
      }
      
    });
});
</script>
<div class="frontshop-button">
  <button id="front-button" type="button" class="scalable frontshop"><span>FrontShop Preview</span></button>
</div>