<script>
var categories = <?php echo $this->getJson() ?>;
var key = '<?php echo Mage::getSingleton('adminhtml/url')->getSecretKey("catalog_product_attribute","edit");?>';
Event.observe(window, 'load', function() {
  $('front-button').observe('click', function() { 
      var id = $$('input[name="general[id]"]')[0].value;
      if(id > 0) {
        var url = categories[id];
        window.open(url);   
      }
  }); 
});
function addEditLinks() {
  $$('table.data thead tr').each(function(item) {
    if(item.readAttribute('class') == 'headings') {
      item.down('.last').removeClassName('last');
      var th = new Element('th');
      th.update('<span class="nobr">Action</span>');
      th.className = 'no-link last';
      th.setStyle({'width':'50px'});
      item.insert(th);
    } else {
      item.down('.last').removeClassName('last');
      var th = new Element('th');
      th.className = 'no-link last'
      item.insert(th);
    }   
  });
  $$('table.data tbody tr').each(function(item) {
    item.down('.last').removeClassName('last');
    var id = item.down('input[type="checkbox"]').value;
    var td = new Element('td');
    td.update('<a href="/admin/catalog_product/edit/id/'+id+'/key/'+key+'/'+'">Edit</a>');
    td.className = 'last';
    item.insert(td);
  }); 
}
</script>
<button id="front-button" type="button" class="scalable " style=""><span>FrontShop Preview</span></button>
<button id="add-edit-button" type="button" class="scalable " onclick="addEditLinks()" style=""><span>Add Edit Links</span></button>