<?php $_type = $this->_getType(); ?>

<?php if (Mage::helper('MvProductivityPack')->isAdminLogged()): ?>

<div id="productivity-panel">
  <div id="productivity-panel-content" class="clear">

  <?php if ($_type == 'product'): ?>
  <a href="<?php echo $this->_getProductLink(); ?>"><?php echo $this->__('Product in admin'); ?></a>
  <?php endif; ?>

  <?php if (($_type == 'page' || $_type == 'index') && ($link = $this->_getCmsPageLink())): ?>
  <a href="<?php echo $link ?>"><?php echo $this->__('CMS page in admin'); ?></a>
  <?php endif; ?>

  <?php if ($_type == 'category' && ($link = $this->_getCategoryLink())): ?>
  <a href="<?php echo $link ?>"><?php echo $this->__('Category in admin'); ?></a>
  <?php endif; ?>

  </div>
</div>
<?php endif ?>
