<?php

$_helper = Mage::helper('MvProductivityPack');
$_type = $this->_getType();

?>

<?php if ($_helper->isAdminLogged()): ?>

<div id="productivity-panel">
  <div id="productivity-panel-content">

  <?php if ($_type == 'product'): ?>
  <a href="<?php echo $this->_getProductLink(); ?>"><?php echo $this->__('Product in admin'); ?></a>
  <?php endif; ?>

  <?php if (($_type == 'page' || $_type == 'index') && ($link = $this->_getCmsPageLink())): ?>
  <a href="<?php echo $link ?>"><?php echo $this->__('CMS page in admin'); ?></a>
  <?php endif; ?>

  <?php if ($_type == 'category'): ?>

  <a href="<?php echo $this->_getWithoutImagesLink() ?>"><?php echo $this->__('Show products without images'); ?></a>

  <?php if ($link = $this->_getCategoryLink()): ?>
  <a href="<?php echo $link ?>"><?php echo $this->__('Category in admin'); ?></a>
  <?php endif; ?>

  <?php endif; ?>

  </div>
</div>

<?php elseif ($_helper->isReviewerLogged() && $_type == 'category'): ?>

<div id="productivity-panel">
  <div id="productivity-panel-content">
    <a href="<?php echo $this->_getWithoutImagesLink() ?>"><?php echo $this->__('Show products without images'); ?></a>
  </div>
</div>

<?php endif; ?>
